# Generated by Django 4.1.5 on 2023-04-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_profile',
            name='room_no',
            field=models.CharField(default='342', max_length=10),
        ),
    ]
