# Generated by Django 4.1.5 on 2023-04-25 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Outpass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Reason', models.TextField(blank=True, max_length=1000, null=True)),
                ('faculty_approval', models.BooleanField(blank=True, null=True)),
                ('warden_approval', models.BooleanField(blank=True, null=True)),
                ('swc_approval', models.BooleanField(blank=True, default=True, null=True)),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('used', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='staff_profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('profile_pic', models.FileField(default='media/default.jpg', max_length=400, upload_to='')),
                ('phone_no', models.CharField(max_length=100)),
                ('Permission_level', models.CharField(max_length=50)),
            ],
        ),
    ]
