# Generated by Django 4.1.5 on 2023-04-28 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff_profile',
            name='gender',
            field=models.CharField(default='female', max_length=50),
        ),
    ]
