# Generated by Django 4.1.5 on 2023-04-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_student_profile_room_no'),
        ('outpass', '0003_staff_profile_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_profile',
            name='students',
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='fa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='role',
            field=models.CharField(default='fa', max_length=50),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='students_fa',
            field=models.ManyToManyField(related_name='staff_profiles_fa', to='users.student_profile'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='students_swc',
            field=models.ManyToManyField(related_name='staff_profiles_swc', to='users.student_profile'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='students_warden',
            field=models.ManyToManyField(related_name='staff_profiles_warden', to='users.student_profile'),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='swc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='staff_profile',
            name='warden',
            field=models.BooleanField(default=False),
        ),
    ]
