# Generated by Django 4.1.5 on 2023-04-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0004_remove_staff_profile_students_staff_profile_fa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff_profile',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
