# Generated by Django 4.1.5 on 2023-04-28 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outpass', '0005_alter_staff_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff_profile',
            name='Permission_level',
        ),
    ]
